# Generated by Django 5.0.6 on 2024-06-28 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('barangay', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='barangay',
        ),
        migrations.DeleteModel(
            name='email',
        ),
        migrations.DeleteModel(
            name='firstname',
        ),
        migrations.DeleteModel(
            name='lastname',
        ),
        migrations.DeleteModel(
            name='password',
        ),
        migrations.DeleteModel(
            name='phone',
        ),
    ]
