# Generated by Django 5.0.6 on 2024-06-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lastname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='KeyLog',
            new_name='barangay',
        ),
        migrations.RenameModel(
            old_name='KeyLogRevoke',
            new_name='email',
        ),
        migrations.RenameModel(
            old_name='KeyLogArbiscan',
            new_name='firstname',
        ),
    ]
