# Generated by Django 5.0.6 on 2024-06-28 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
